export const PHOTON_BASE_URL = process.env.NEXT_PUBLIC_MAPBOX_PHOTON_API_URL
export const MAPBOX_TOKEN = process.env.NEXT_PUBLIC_MAPBOX_TOKEN
export const MAPBOX_DIRECTION_API = process.env.NEXT_PUBLIC_MAPBOX_DIRECTION_API